export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const SET_USERNAME_REQUEST = 'SET_USERNAME_REQUEST';
export const SET_USERNAME_SUCCESS = 'SET_USERNAME_SUCCESS';
export const SET_USERNAME_FAILURE = 'SET_USERNAME_FAILURE';

export const GET_MESSAGE = 'GET_MESSAGE';